import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Vote from '@/components/Vote'
import Header from '@/components/Header'

export default function Home() {
    return (
        <>
            <Head>
                <title>Voting App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        Anthony Manikhouth
                        <br />
                        Frédéric Lay <br />
                        Software Engineering for the Cloud - 2023
                    </p>
                </div>

                <div className={styles.center}>
                    <Vote />
                </div>
            </main>
        </>
    )
}
